# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDsag():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_dsag(self):
    self.driver.get("http://localhost:8069/web#cids=1&menu_id=5&action=37&model=ir.module.module&view_type=kanban")
    self.driver.set_window_size(1440, 560)
    self.driver.find_element(By.LINK_TEXT, "Update Apps List").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > .btn-primary > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > .btn-primary > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".oe_module_vignette:nth-child(28) .dropdown-toggle").click()
    self.driver.find_element(By.CSS_SELECTOR, ".show > .dropdown-item:nth-child(2)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oe_module_vignette:nth-child(28) > .oe_module_desc .btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.close()
  
